### ISSUE TITLE
Support for UTF8

### ISSUE THREAD

**Issue by alvarengasv** [techouse/mysql-to-sqlite3#10]
**Is your feature request related to a problem? Please describe.**
When converting a database that has utf8 characters the values are converted to numeric values. For example Произошла is turned to 208,159,209,128,208,190,208,184,208,183,208,190,209,136,208,187,208,176

**Describe the solution you'd like**
It should convert the characters correctly. Maybe add a --utf8 parameter to enable utf8 support.

**Comment by techouse** [comment]
It does support UTF-8 and does no encoding/transcoding by itself. May I ask for your DDL as this looks more like a database misconfig.

**Comment by alvarengasv** [comment]
Sorry it was my fault. I was using python 2.7. My mysql2sqlite didn't even have --version. I updated to Python 3.8 and the conversion worked. Thanks for your help!

**Comment by techouse** [comment]
Aha. So it's another Python 2 thing. Python 2 is notorious for its lack of UTF-8 support.

**Comment by alvarengasv** [comment]
It's python 2.7 on windows. Pip says mysql-to-sqlite is 1.3.0
On python 3.8 it's 1.3.3

**Comment by techouse** [comment]
Could you update that 2.7 installation to have 1.3.3 and paste the --version output here please.

**Comment by alvarengasv** [comment]
When I execute pip install mysql-to-sqlite3 it installs 1.3.0. That version won't accept --version

I also updated pip but it won't install any newer version of mysql-to-sqlite3 on python 2.7

**Comment by alvarengasv** [comment]
I have confirmed it works correctly with utf8 on python 2.7 after updating to 1.3.3
