### ISSUE TITLE
Suggest IF NOT EXISTS when creating indexes

### ISSUE THREAD

**Issue by juliangall** [techouse/mysql-to-sqlite3#11]
**Is your feature request related to a problem? Please describe.**
I ran mysql-to-sqlite3 a second time to refresh my db, but it errored due to not being able to create the indexes, because they were created the first time I ran it.

**Describe the solution you'd like**
Add IF NOT EXISTS to the CREATE INDEX SQL command.

**Describe alternatives you've considered**
None.

**Additional context**
I can see no downsides to this.

Thanks,

Julian

**Comment by techouse** [comment]
Done. Released in v1.3.5

**Comment by juliangall** [comment]
You're a star! Thank you.
