### ISSUE TITLE
A project like this is way overdue !!

### ISSUE THREAD

**Issue by webquest-nz** [techouse/mysql-to-sqlite3#12]
I am going to try this out.  This has been a constant bugbear, the lack of tools to do this.  Most of the converters I've seen on Google didn't even work on current versions of MySQL.  All Kudos to this project.  Good to see it is in Python also as I am more familiar with Python than anything else.

**Comment by techouse** [comment]
Hehe, enjoy :)

**Comment by kylemanna** [comment]
Here to say "thanks" as well.  Installed it and it just worked.  Excited to see all the attention to detail with code quality badges and the like.

🙏🙏🙏

**Comment by techouse** [comment]
Thanx @kylemanna 😇
