### ISSUE TITLE
Possible to transfer the structure only?

### ISSUE THREAD

**Issue by klodoma** [techouse/mysql-to-sqlite3#13]
I have use-cases where I want the whole DB structure to be transferred from mysql to sqlite and then just some table content. 

I couldn't find an option to do the transfer without data. Is it possible?

**Comment by techouse** [comment]
Currently, the tool offers no such functionality and I'm not going to add it as transferring a DDL is somewhat trivial and can be easily done by either using a database administration tool, e.g. DBeaver or by simply transferring the whole database and then delete the content of those tables.
