### ISSUE TITLE
Limit amount of rows gathered from a table

### ISSUE THREAD

**Issue by CurtisTD** [techouse/mysql-to-sqlite3#17]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to limit how much data it gathers from each table (e.g., 50 rows or so). I attempt to generate test data files, and this works great, but it's pretty much the same as exporting the entire database if I want test data from each table.

**Describe the solution you'd like**
Add a row limit option, such as "-r 50", which will only grab the first(?) 50 entries from what's returned.

**Describe alternatives you've considered**
I've tried connecting to the database and parsing it myself, but it get messy. This tool works great, but would be much more helpful if we could limit the amount of entries gathered.

Edit:
Maybe limit the number of chunks instead of rows?
Possibly even add a "--where" options, similar to how mysqldump handles it.

**Comment by techouse** [comment]
Hey,

I'll look into adding this feature in the coming release.

**Comment by techouse** [comment]
Added `-L`, `--limit-rows` CLI option. Default is `0`.
