### ISSUE TITLE
add NOCASE params when mysql is no case in default 

### ISSUE THREAD

**Issue by luyinhua** [techouse/mysql-to-sqlite3#18]
mysql default is NOCASE in char/varchar/text field , but sqlite is default is not nocase ,can the command  add a params to change nocase info 

such as 

CREATE TABLE User (UserName NVARCHAR(20) `COLLATE NOCASE`);

**Comment by techouse** [comment]
Hey,

Thanx for the idea proposal. I'll add it probably over the coming weekend. :)

**Comment by techouse** [comment]
Added `-C`, `--collation` CLI option. [It defaults to `BINARY` just like specified in the SQLite docs.](https://www.sqlite.org/lang_createtable.html#the_collate_clause)
