### ISSUE TITLE
How do I run this thing?

### ISSUE THREAD

**Issue by damms005** [techouse/mysql-to-sqlite3#21]
I am new to Python and I saw this tool. As I have python already installed on my linux box, I thought it will be straight-forward for newbies like me, but oops, here I am!

After installing the package following the instruction using `pip`, no command named `mysql2sqlite` is available on the command line. I have not personally directly used anything installed with pip, so that may explain a lot about my issue.

I have tried creating a python script and importing the package `mysql2sqlite`. I have also tried using `pip show mysql-to-sqlite3` to get the location of the package and added same to my `PATH` but still no luck.

How do I use this package?

**Comment by techouse** [comment]
Hey!

So if you installed everything correctly it should expose the console command `mysql2sqlite` [as it's defined in the setup.py file](https://github.com/techouse/mysql-to-sqlite3/blob/master/setup.py#L70).

I'm not entirely sure how you installed it though.

Try and follow these steps:

- on Linux / macOS
  ```bash
  python3 -m venv env
  source env/bin/activate
  pip install mysql-to-sqlite3
  mysql2sqlite --help
  ```

- on MS Windows using CMD
  ```cmd
  python -m venv env
  env\Scripts\activate.bat
  pip install mysql-to-sqlite3
  mysql2sqlite --help
  ```

- on MS Windows using PowerShell
  ```ps1
  python -m venv env
  env\Scripts\Activate.ps1
  pip install mysql-to-sqlite3
  mysql2sqlite --help
  ```
