### ISSUE TITLE
Broken Compatibility with MariaDB < 10.2 

### ISSUE THREAD

**Issue by AceScottie** [techouse/mysql-to-sqlite3#30]
Unit tests are not compatible with MariaDB-server <= 10.1

JSON alias was only release as part of 10.2 for LONGTEXT, but is used in a query from /uint/mysql_to_sqlite3_test.py

Also can you add a check if the DB exists before running tests (or a big warning). I provided a db name of an existing db which ended up being deleted (i have backup and its from an old project so no loss)

**Comment by techouse** [comment]
I'm not sure where it fails as the tests quite obviously cover this. Check yourself [here](https://github.com/techouse/mysql-to-sqlite3/runs/6129973423?check_suite_focus=true).

If you check the tests, specifically the [model factories](https://github.com/techouse/mysql-to-sqlite3/blob/master/tests/models.py#L112), you'd see that I check for an environment variable called `LEGACY_DB`. I then set that in my [Github actions here](https://github.com/techouse/mysql-to-sqlite3/blob/master/.github/workflows/test.yml#L137).

**Comment by techouse** [comment]
Also, checking if a database already exists for a test is kinda overkill. Just create a test server or a test DB or just use a Docker image.
