### ISSUE TITLE
Many thanks!

### ISSUE THREAD

**Issue by ncgoodbody** [techouse/mysql-to-sqlite3#33]
This isn't a real feature request. Just wanted to thank you. This tool saved me a ton of work today. Appreciate you putting it out into the world!

**Comment by techouse** [comment]
Hehe, I'm glad you found it useful.

**Comment by elvis2** [comment]
@ncgoodbody I too want to say thanks! I was able to convert a Drupal mysql db to sqlite in seconds. 😁

**Comment by jzohrab** [comment]
Thank you also!  I'm working on a personal project and wanted to try to convert the code to a different db, this got the test db set up very quickly.  Cheers and thank you again for the great project.
