### ISSUE TITLE
Unknown character set: 'utf8mb4'

### ISSUE THREAD

**Issue by snblackout** [techouse/mysql-to-sqlite3#4]
Installed Python 3.8.1 on Windows 10, used pip to install, tried to run the command on a test schema and a single table with just an id and varchar column with 1 row with 'test' in column.

Any ideas what's causing this?

```
C:\Users\User>mysql2sqlite --sqlite-file "C:\Temp\testdb.db" --mysql-database "sqlite_test" --mysql-user user --mysql-password pass
2020-02-04 18:33:43 ERROR    1115 (42000): Unknown character set: 'utf8mb4'
1115 (42000): Unknown character set: 'utf8mb4'
```

**Comment by techouse** [comment]
Hmm... what's your MySQL version? According to the error your MySQL does not support utf8mb4, which was added in v5.5.4 (I think), however, I do not know why that would be an issue to be honest. I will investigate once I have some free time.

**Comment by techouse** [comment]
@snblackout can you supply me with a dump of the MySQL database you are trying to transfer?

**Comment by snblackout** [comment]
@techouse thanks for your reply.  I think you're correct in the MySQL version.  We're kinda locked into an older version (because embedded systems) for the time being. So we're on 5.1.72 right now and will have to research the task it'll take to upgrade to something a bit newer.

**Comment by techouse** [comment]
Whoa, that's old. Well good luck with that, I've done migrations like these in the past and they are by no mean an easy task 😞

**Comment by snblackout** [comment]
Yup.  We can do system wide updates though, so not a huge task, just need plenty of testing because you don't want to "brick" them with a bad database configuration.
