### ISSUE TITLE
Future feature annotations is not defined

### ISSUE THREAD

**Issue by macias** [techouse/mysql-to-sqlite3#55]
**Describe the bug**

I tried to run the program for the first time.

**Expected behaviour**

Conversion or human-friendly error.

**Actual result**

I got this error:
```
Traceback (most recent call last):
  File "/home/mist/.local/bin/mysql2sqlite", line 5, in <module>
    from mysql_to_sqlite3.cli import cli
  File "/home/mist/.local/lib/python3.6/site-packages/mysql_to_sqlite3/__init__.py", line 4, in <module>
    from .transporter import MySQLtoSQLite
  File "/home/mist/.local/lib/python3.6/site-packages/mysql_to_sqlite3/transporter.py", line 14, in <module>
    import mysql.connector
  File "/home/mist/.local/lib/python3.6/site-packages/mysql/connector/__init__.py", line 32, in <module>
    from .connection_cext import CMySQLConnection
  File "/home/mist/.local/lib/python3.6/site-packages/mysql/connector/connection_cext.py", line 40, in <module>
    from .abstracts import MySQLConnectionAbstract
  File "/home/mist/.local/lib/python3.6/site-packages/mysql/connector/abstracts.py", line 33
    from __future__ import annotations
    ^
```

**System Information**

```bash
$ mysql2sqlite --version
```

This gives the same error as above :-).

openSUSE 15.3 64-bit, Python 3.6.15

**Additional context**
In case of errors please run the same command with `--debug`. This option is only available on v1.4.12 or greater.

It gives exactly the same error.

**Comment by techouse** [comment]
Hey!

What version where you trying to run? Since v2.0.0 Python 3.6 is not supported anymore.

**Comment by macias** [comment]
Thank you for quick reply. The latest one, I didn't notice support note. Ok, this explains the problems, once again many thanks for your help.

**Comment by techouse** [comment]
No problem. :)

It's intriguing though that it allowed you to install v2 even though [I've specifically limited it to 3.7+](https://github.com/techouse/mysql-to-sqlite3/blob/master/pyproject.toml#L10)

**Comment by macias** [comment]
Well, I guess it is the latest one, because I didn't pass any special parameters to pip. But my knowledge of pip/python is very limited.

**Comment by macias** [comment]
You are too fast, I updated my previous post :-).

**Comment by techouse** [comment]
> So, in theory it should work with python 3.6, correct?

Theoretically yes, [but the last time it's been tested against 3.6 was like 1y ago](https://github.com/techouse/mysql-to-sqlite3/actions/runs/2964304517/jobs/4743889995) in v1.4.14.

So you might want to install that specific version as it's known to still work with 3.6.

**Comment by macias** [comment]
Ha! It worked :-). Thank you very much (and I know more about pip as well :-D).

**Comment by techouse** [comment]
However, this looks more like an issue with [mysql-connector-python](https://github.com/mysql/mysql-connector-python). That one dropped Python 3.6 support in [v8.0.29](https://github.com/mysql/mysql-connector-python/blob/trunk/CHANGES.txt#L93), so you might want to install `pip install mysql-connector-python==8.0.28`
