### ISSUE TITLE
KeyError: 'ssl_disabled'

### ISSUE THREAD

**Issue by andreaskoelsch** [techouse/mysql-to-sqlite3#70]
**Describe the bug**
When trying to connect to a MySQL Server, the `mysql-connector-python` throws `KeyError: 'ssl_disabled'`

**Expected behaviour**
Connection works

**Workaround**
Commenting transporter.py:126 solves the issue. Not sure if this is the intended solution, so not creating a PR

**Comment by techouse** [comment]
Hi,

Have you tried disabling SSL using the `-S` switch?

Can you please provide all the info the template requested?

**Comment by andreaskoelsch** [comment]
Yes, I have. The problem is, that the key is no longer existing in mysql-connector-python, so setting it to False will cause a KeyError, too. Sorry for not filling the template. I'm using the latest version of mysql-to-sqlite3, here's the output of `mysql2sqlite --version`

```
| software               | version                              |
|------------------------|--------------------------------------|
| mysql-to-sqlite3       | 2.1.10                               |
|                        |                                      |
| Operating System       | Windows 10                           |
| Python                 | CPython 3.9.19                       |
| MySQL                  | MySQL client not found on the system |
| SQLite                 | 3.41.2                               |
|                        |                                      |
| click                  | 8.1.7                                |
| mysql-connector-python | 2.2.9                                |
| python-slugify         | 8.0.4                                |
| pytimeparse2           | 1.7.1                                |
| simplejson             | 3.19.2                               |
| tabulate               | 0.9.0                                |
| tqdm                   | 4.66.2                               |

```

**Comment by andreaskoelsch** [comment]
Ohh.. now I understand. mysql-connector-python is the successor of mysql-connector. I thought they were independent packages. After removing mysql-connector and reinstalling mysql-connector-python it's working again. Consider this closed. Thanks for the hint!
