### ISSUE TITLE
Field type is bit (1)

### ISSUE THREAD

**Issue by jackwei** [techouse/mysql-to-sqlite3#74]
**Describe the bug**

Mysql  Field type is bit (1), default value is 0 

 ERROR    SQLite failed creating table test : near "0": syntax error
near "0": syntax error

**Expected behaviour**
What you expected.

**Actual result**
What happened instead.

**System Information**

```bash
$ mysql2sqlite --version
```

```
<paste here>
```

This command is only available on v1.3.2 and greater. Otherwise, please provide some basic information about your system (Python version, operating system, etc.).

**Additional context**

In case of errors please run the same command with `--debug`. This option is only available on v1.4.12 or greater.

**Comment by techouse** [comment]
Hi.

Can you please provide more information on how to reproduce this and a DDL I could test this against?

**Comment by techouse** [comment]
Duplicate of #75
