### ISSUE TITLE
【bug report 】Syntax error encountered when converting MySQL table to SQLite using mysql2sqlite

### ISSUE THREAD

**Issue by TigerCatRabbit** [techouse/mysql-to-sqlite3#75]
**Describe the bug**
I encountered a syntax error when using the mysql2sqlite tool to convert a MySQL database to a SQLite database. The error occurred while trying to create a table named ops_sms_sent.

**Actual result**
Error Message:
sqlite3.OperationalError: near "1": syntax error

**Original ddl :**
CREATE TABLE `ops_sms_sent` (
  `sms_id` varchar(32) NOT NULL,
  `MSG_LOCAL_ID` int NOT NULL DEFAULT '0',
  `MSG_ID` varchar(32) DEFAULT '0',
  `PK_TOTAL` tinyint NOT NULL DEFAULT '1',
  `PK_NUMBER` tinyint NOT NULL DEFAULT '1',
  `REQ_REPORT` bit(1) NOT NULL DEFAULT b'1',
  `SEND_TIME` datetime NOT NULL,
  `SOURCE_ADDR` varchar(21) DEFAULT '0',
  `DEST_ADDR` varchar(21) NOT NULL,
  `CONTENT` varchar(1000) NOT NULL DEFAULT '',
  `REQUEST_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ROUTE_ID` varchar(50) DEFAULT NULL,
  `USER_ID` varchar(32) NOT NULL,
  `sms_param` varchar(3000) DEFAULT NULL,
  `SEND_RESULT` int NOT NULL DEFAULT '0',
  `SMS_STATUS` varchar(20) DEFAULT NULL,
  `STATUS_TIME` datetime DEFAULT NULL,
  `sms_status_filter` varchar(128) DEFAULT NULL,
  `batch_id` varchar(32) DEFAULT NULL,
  `USER_NAME` varchar(64) DEFAULT NULL,
  `free_count` int NOT NULL DEFAULT '1',
  `conn_name` varchar(255) DEFAULT NULL,
  KEY `SEND_TIME` (`SEND_TIME`,`DEST_ADDR`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3;

**Additional Context:**
The error seems to be related to the syntax near the default value '1'. It's possible that the conversion tool is not handling the MySQL to SQLite syntax differences correctly, especially around data types and default values.
**System Information**

```bash
$ mysql2sqlite --version
```

```
| software               | version                                                           |
|------------------------|-------------------------------------------------------------------|
| mysql-to-sqlite3       | 2.1.11                                                            |
|                        |                                                                   |
| Operating System       | Linux 6.5.0-27-generic                                            |
| Python                 | CPython 3.8.5                                                     |
| MySQL                  | mysql  Ver 8.0.36-0ubuntu0.22.04.1 for Linux on x86_64 ((Ubuntu)) |
| SQLite                 | 3.41.2                                                            |
|                        |                                                                   |
| click                  | 8.1.7                                                             |
| mysql-connector-python | 8.3.0                                                             |
| python-slugify         | 8.0.4                                                             |
| pytimeparse2           | 1.7.1                                                             |
| simplejson             | 3.19.2                                                            |
| tabulate               | 0.9.0                                                             |
| tqdm                   | 4.66.2                                                             |
```

This command is only available on v1.3.2 and greater. Otherwise, please provide some basic information about your system (Python version, operating system, etc.).

**Debug context**
  File “-/anaconda3/envs/demo/lib/python3.8/site-packages/mysql_to_sqlite3/cli.py", line 182, in cli
    converter.transfer()
  File "-/anaconda3/envs/demo/lib/python3.8/site-packages/mysql_to_sqlite3/transporter.py", line 674, in transfer
    self._create_table(table_name)  # type: ignore[arg-type]
  File "-/anaconda3/envs/demo/lib/python3.8/site-packages/mysql_to_sqlite3/transporter.py", line 544, in _create_table
    self._sqlite_cur.executescript(self._build_create_table_sql(table_name))
sqlite3.OperationalError: near "1": syntax error

**Comment by techouse** [comment]
Hmm, most likely related to the `bit` column.
